config/routes.rb
Rails.application.routes.draw do
  # Configuración de rutas de Devise
  devise_for :users, controllers: { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  # Defines the route for "splash/index"
  get "/splash/index", to: "splash#index"

  # Defines RESTful routes
  resources :categories do
    resources :transactions, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :category_transactions
  has_many :related_transactions, through: :category_transactions, source: :related_transaction

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    related_transactions.sum(:amount)
  end
end

app/models/category_transaction.rb
class CategoryTransaction < ApplicationRecord
  belongs_to :related_category, class_name: 'Category', foreign_key: 'category_id'
  belongs_to :related_transaction, class_name: 'Transaction', foreign_key: 'transaction_id'
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :category_transactions
  has_many :related_categories, through: :category_transactions, source: :related_category

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions, foreign_key: 'author_id'
  has_many :categories, foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_icons, only: %i[new create]

  def new
    @category = Category.new
    @category.icon = @icons.first
  end

  def create
    @category = Category.new(category_params)
    @category.author_id = current_user.id

    if @category.save
      redirect_to root_path, notice: 'Category created successfully'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def set_icons
    @icons = %w[attach_money shopping_cart restaurant
                directions_bus sports_esports home_repair_service
                favorite school move_to_inbox]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @categories = Category.where(author: current_user)
    else
      redirect_to splash_index_path
    end
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category

  def index
    @transactions = @category.related_transactions.order(created_at: :desc)
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = @category.related_transactions.build(transaction_params)
    @transaction.author = current_user

    categories_ids = params[:transaction][:related_categories].reject(&:empty?)

    if categories_ids.present?
      if @transaction.save
        categories_ids.each do |category_id|
          CategoryTransaction.create(category_id:, transaction_id: @transaction.id)
        end
        redirect_to category_transactions_path(@category)
      else
        flash[:alert] = 'Transaction could not be saved.'
        render :new
      end
    else
      flash[:alert] = 'Please select at least one category.'
      render :new
    end
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def transaction_params
    params.require(:transaction).permit(:amount, :name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])

    return unless @user.nil?

    flash[:alert] = 'User not found'
    redirect_to users_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<div id="new-category" class="full-screen bg-ligther">
  <div class="header center d-flex">
    <%= link_to root_path, class: "absolute-start white-color" do %>
      <span class="material-symbols-outlined">
        arrow_back_ios
      </span>
    <% end %>
    <h2>Add a new category</h2>
  </div>
  <%= form_for @category, url: categories_path, html: { multipart: true } do |f| %>
    <div class="form-inputs form-group">
      <%= f.text_field :name, class: "input-field form-control", required: true, placeholder: "Category Name" %>
    </div>
    <div class="category_item d-flex column g-1">
      <h2 class="category_title">Choose one icon</h2>
      <div class="d-flex align-center g-1">
        <%= f.label :icon, "Category Icon", class: "grey-color" %>
        <%= f.select :icon, options_for_select(@icons.map { |icon| [icon, icon] }), {}, { id: "icon-select", class: "form-select form-control material-symbols-outlined", required: true } %>
      </div>
    </div>
    <div class="form-actions w-100 outline-white absolute-bottom">
      <%= f.submit "Save", class: "btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div id="home" class="full-screen bg-ligther">
  <div class="header center d-flex">
    <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "absolute-start white-color" do %>
      <span class="material-symbols-outlined">
        logout
      </span>
    <% end %>
    <h2>Home</h2>
  </div>
  <div class="p-1 d-flex space-between w-100 sub-header">
    <h2 class="category_title">Total of all transactions</h2>
    <p class="category_total"><%= number_to_currency(current_user.transactions.sum(:amount), unit: "$", precision: 2) %></p>
  </div>
  <% if @categories.any? %>
    <% @categories.each do |category| %>
      <%= link_to category_transactions_path(category) do %>
        <div class="category_item d-flex g-1">
          <span class="material-symbols-outlined category_icon center"><%= category.icon %></span>
          <div class="d-flex space-between w-100 mt-1">
            <h2 class="category_title"><%= category.name %></h2>
            <p class="category_total"><%= number_to_currency(category.total_amount, unit: "$", precision: 2) %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="category_item d-flex g-1 center">
      <small class="no-transactions grey-color italic">No categories added yet</small>
    </div>
  <% end %>
  <div class="w-100 outline-white absolute-bottom p-1 d-flex center fixed-bottom">
    <%= link_to 'Add a new category', new_category_path, class: "btn-secondary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Personal BudgetApp</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div id="intro-screen" class="d-flex center full-screen">
  <%= image_tag "logo_white.png", id: "intro-screen_logo" %>
</div>
<div id="splash-screen" class="d-flex center full-screen p-1 fade-in">
  <div id="splash-screen_container" class="d-flex column w-100 h-100 space-between">
    <%= image_tag "logo_dark.png", id: "splash-screen_logo", class: "m-auto" %>
    <div>
      <p class="notice center italic"><%= notice %></p>
      <p class="alert center italic"><%= alert %></p>
    </div>
    <div id="splash-screen_btns" class="d-flex column mt-auto">
      <%= link_to "Login", new_user_session_path, class: "btn-primary" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn-grey-outline" %>
    </div>
  </div>
</div>

app/views/transactions/index.html.erb
<div id="transactions" class="full-screen bg-ligther">
  <div class="header center d-flex">
    <%= link_to root_path, class: "absolute-start white-color" do %>
      <span class="material-symbols-outlined">
        arrow_back_ios
      </span>
    <% end %>
    <h2 class="d-flex center g-1">
      <span class="material-symbols-outlined" style="font-size: inherit;">
        <%= @category.icon %>
      </span>
      <%= @category.name %>
    </h2>
  </div>
  <div class="p-1 d-flex space-between w-100 sub-header">
    <h2 class="category_title">Category Total</h2>
    <p class="category_total"><%= number_to_currency(@category.total_amount, unit: "$", precision: 2) %></p>
  </div>
  <% if @transactions.any? %>
    <div id="transactions_list" class="p-1">
      <ul class="transaction-list">
        <% @transactions.each do |transaction| %>
          <li class="transaction-item">
            <div class="transaction-details d-flex column">
              <div class="d-flex space-between w-100">
                <h2 class="category_title"><%= transaction.name %></h2>
                <p class="category_total"><%= number_to_currency(transaction.amount, unit: "$", precision: 2) %></p>
              </div>
              <small class="transaction-date end-self d-flex align-center italic grey-color">
                <span class="material-symbols-outlined">
                  history
                </span>
                <%= time_ago_in_words(transaction.created_at) %>
              </small>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <div id="transactions_list" class="p-1 d-flex center">
      <small class="no-transactions italic grey-color">No transactions in this category yet.</small>
    </div>
  <% end %>
  <div class="w-100 outline-white absolute-bottom p-1 d-flex center fixed-bottom">
    <%= link_to new_category_transaction_path(@category), class: "btn-secondary" do %>
      Add a new transaction
    <% end %>
  </div>
</div>

app/views/transactions/new.html.erb
<div id="new-transaction" class="full-screen bg-ligther">
  <div class="header center d-flex">
    <%= link_to category_transactions_path(@category), class: "absolute-start white-color" do %>
      <span class="material-symbols-outlined">
        arrow_back_ios
      </span>
    <% end %>
    <h2>Add a new transaction</h2>
  </div>
  <%= form_for @transaction, url: category_transactions_path(@category) do |f| %>
    <div class="form-inputs form-group">
      <%= f.text_field :name, class: "input-field form-control", required: true, placeholder: "Name" %>
      <%= f.number_field :amount, class: "input-field form-control", required: true, placeholder: "Amount" %>
    </div>
    <div id="categories_list" class="form-check p-1 d-flex column g-1">
      <h2 class="category_title">Choose at least one category</h2>
      <% if flash[:alert].present? %>
        <small class="alert center italic warning-color"><%= flash[:alert] %></small>
      <% end %>
      <%= f.collection_check_boxes :related_categories,
          Category.where(author: current_user),
          :id,
          :name,
          { checked: @transaction.related_category_ids } do |b| %>
        <div class="category_element d-flex">
          <%= b.check_box(class: "form-check-input") %>
          <span class="material-symbols-outlined"><%= b.object.icon %></span>
          <%= b.label(class: "form-check-label") %>
        </div>
      <% end %>
    </div>
    <div class="form-actions w-100 outline-white absolute-bottom">
      <%= f.submit "Save", class: "btn-secondary" %>
    </div>
  <% end %>
</div>